hello:
	nasm -felf64 hello.asm && ld hello.o && ./a.out
putchar:
	nasm -felf64 putchar.asm && ld putchar.o && ./a.out
try:
	nasm -felf64 try.asm && ld try.o && ./a.out


.PHONY: hello try
.SILENT: hello try